DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'nldb_user') THEN
      CREATE ROLE nldb_user LOGIN PASSWORD 'CHANGE_ME_STRONG_PASSWORD';
   END IF;
END
$$;

REVOKE ALL ON DATABASE nldb FROM PUBLIC;
GRANT CONNECT ON DATABASE nldb TO nldb_user;

\c nldb

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO nldb_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nldb_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nldb_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nldb_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO nldb_user;
